version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.1
    - 12.8.3
    - 13.0.0
    - 13.0.1
    - 13.0.13
    - 13.0.16
    - 13.0.2
    - 13.0.6
    - 13.0.7
    - 13.1.1
    - 13.1.2
    - 13.1.5
  - dependency-name: recharts
    versions:
    - 2.0.6
    - 2.0.7
    - 2.0.8
    - 2.0.9
  - dependency-name: react-dom
    versions:
    - 17.0.2
    - 17.0.2
  - dependency-name: react
    versions:
    - 17.0.2
  - dependency-name: react-dev-utils
    versions:
    - 11.0.4
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
